version: '3.4'

services:
  danskebank.api.main:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8000:80"
      - "8443:443"
    networks:
      danskebank-network:
        aliases:
          - api01.danskebank.com

  danskebank-mssql-server-linux:
    ports:
      - "1433:1433"
    networks:
      danskebank-network:
        aliases:
          - db01.danskebank.com