version: '3.4'

services:
  danskebank.api.main:
    image: ${DOCKER_REGISTRY-}danskebankapi
    build:
      context: .
      dockerfile: API/DanskeBank.API/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  danskebank-mssql-server-linux:
    image: microsoft/mssql-server-linux:latest
    volumes:
      - ./danskebankdata/mssql:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=My_pass$$

networks:
  danskebank-network:
    driver: bridge